node "_task_clean-output.js"
node "generate-code_core-models.js"
node "generate-code_daos.js"
node "generate-code_entities.js"
node "generate-code_filters.js"
node "generate-code_repositories.js"
node "generate-code_core-templates.js"
node "_task_copy-files-to-framework.js"